# Generated by Django 5.1.4 on 2024-12-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchroom_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rooms',
        ),
    ]
