# Generated by Django 5.1.4 on 2024-12-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchroom_app', '0002_remove_user_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(related_name='room_users', to='lunchroom_app.user'),
        ),
    ]
