# Generated by Django 5.1.4 on 2024-12-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchroom_app', '0003_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='foods',
            field=models.ManyToManyField(related_name='room_foods', to='lunchroom_app.fooditem'),
        ),
    ]
