# Generated by Django 5.1.4 on 2024-12-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchroom_app', '0004_room_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='room',
        ),
    ]
